name: gemu
description: Network by Gamers for you.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  bubble: ^1.2.1
  cached_network_image: ^3.0.0
  # camera: ^0.9.4+6
  carousel_slider: ^4.0.0-nullsafety.0
  cloud_firestore: ^2.0.0
  firebase_auth: ^1.2.0
  firebase_storage: ^8.0.5
  flutter_image_compress: ^1.0.0
  flutter_riverpod: ^1.0.2
  flutter_svg: ^1.0.3
  google_fonts: ^2.0.0
  helpers: ^1.1.2 
  image_cropper: ^1.4.0
  image_picker: ^0.7.4
  intro_slider: ^2.4.1
  provider: ^5.0.0
  shared_preferences: ^2.0.5
  sliding_up_panel: ^2.0.0+1
  stacked: ^2.1.1
  timeago: ^3.0.2
  video_player: ^2.1.1 
  expandable: ^5.0.1
  video_thumbnail: ^0.4.3
  modal_bottom_sheet: ^2.0.0
  bouncing_widget: ^2.0.0
  marquee: ^2.2.0
  chewie: ^1.2.2
  flutter_cache_manager: ^3.1.2
  visibility_detector: ^0.2.2
  firebase_analytics: ^8.2.0
  cloud_functions: ^3.0.3
  algolia: ^1.0.1
  sticky_headers: ^0.2.0
  country_calling_code_picker: ^2.0.0
  loader: ^1.0.0
  flutter_overlay_loader: ^1.0.3
  loading_indicator: ^3.0.2
  material_design_icons_flutter: ^5.0.6595
  flutter_datetime_picker: ^1.5.1
  connectivity_plus: ^2.2.1
  email_validator: ^2.0.1
  # video_compress: ^3.1.0
  ## TODO attendre une nouvelle version du package video_compress afin d'enlever le git ##
  video_compress:
    git:
      url: https://github.com/jonataslaw/VideoCompress.git
      ref: master


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_native_splash: ^1.3.3

flutter_native_splash:
  color: "#E0EFFF"
  color_dark: "#22213C"
  fullscreen: true
  image: assets/icons/icon_splash.png
  android: true
  android_12: 
    image: assets/icons/icon_splash.png
  ios: true
  web: false

flutter_launcher_name:
  name: "Gemu"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/icons/
    - assets/images/
